package ArduinoML.sandbox;

/*Generated by MPS */


public class map_App {
  public static void main(String[] args) {
    System.out.println("//Code generated by ArduinoML");
    System.out.println("void setup(){");
    System.out.println("    pinMode(" + 10 + ", OUTPUT);");
    System.out.println("    pinMode(" + 9 + ", INPUT);");
    System.out.println("}");
    System.out.println("\n// Behavioral concepts");
    System.out.println("long time = 0; long debounce = 200;\n");

    System.out.println("void state_" + "1" + "() {");
    System.out.println("   boolean guard = millis() - time > debounce;");
    System.out.println("   if (digitalRead(" + 9 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "2" + "(); ");
    System.out.println("   }");
    System.out.println("   state_" + "1" + "();");
    System.out.println("}\n");

    System.out.println("void state_" + "2" + "() {");
    System.out.println("   digitalWrite(" + 10 + ", HIGH" + ");");
    System.out.println("   delayMicroseconds(" + 3830 + "/2);");
    System.out.println("   digitalWrite(" + 10 + ", LOW" + ");");
    System.out.println("   delayMicroseconds(" + 3830 + "/2);");
    System.out.println("   digitalWrite(" + 10 + ", HIGH" + ");");
    System.out.println("   delayMicroseconds(" + 3400 + "/2);");
    System.out.println("   digitalWrite(" + 10 + ", LOW" + ");");
    System.out.println("   delayMicroseconds(" + 3400 + "/2);");
    System.out.println("   boolean guard = millis() - time > debounce;");
    System.out.println("   if (digitalRead(" + 9 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "1" + "(); ");
    System.out.println("   }");
    System.out.println("   state_" + "2" + "();");
    System.out.println("}\n");


    System.out.println("\nvoid loop() { state_" + "1" + "(); } // Entering init state\n");



  }
}
