package ArduinoML.sandbox;

/*Generated by MPS */


public class map_App {
  public static void main(String[] args) {
    System.out.println("//Code generated by ArduinoML");
    System.out.println("void setup(){");
    System.out.println("    pinMode(" + 12 + ", OUTPUT);");
    System.out.println("    pinMode(" + 9 + ", INPUT);");
    System.out.println("    pinMode(" + 10 + ", INPUT);");
    System.out.println("}");
    System.out.println("\n// Behavioral concepts");
    System.out.println("long time = 0; long debounce = 200;\n");

    System.out.println("void state_" + "off" + "() {");
    System.out.println("   boolean guard = millis() - time > debounce;");
    System.out.println("   if (digitalRead(" + 9 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "melodyA1" + "(); ");
    System.out.println("   }");
    System.out.println("   if (digitalRead(" + 10 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "melodyB1" + "(); ");
    System.out.println("   }");
    System.out.println("   state_" + "off" + "();");
    System.out.println("}\n");

    System.out.println("void state_" + "melodyA1" + "() {");
    System.out.println("   for(int i=0;i<" + 3 + ";i++){");
    System.out.println("       digitalWrite(" + 12 + ", HIGH" + ");");
    System.out.println("       delayMicroseconds(" + 3830 + "/2);");
    System.out.println("       digitalWrite(" + 12 + ", LOW" + ");");
    System.out.println("       delayMicroseconds(" + 3830 + "/2);");
    System.out.println("   }");

    System.out.println("   for(int i=0;i<" + 3 + ";i++){");
    System.out.println("       digitalWrite(" + 12 + ", HIGH" + ");");
    System.out.println("       delayMicroseconds(" + 3400 + "/2);");
    System.out.println("       digitalWrite(" + 12 + ", LOW" + ");");
    System.out.println("       delayMicroseconds(" + 3400 + "/2);");
    System.out.println("   }");

    System.out.println("   boolean guard = millis() - time > debounce;");
    System.out.println("   if (digitalRead(" + 9 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "melodyA2" + "(); ");
    System.out.println("   }");
    System.out.println("   if (digitalRead(" + 10 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "melodyB2" + "(); ");
    System.out.println("   }");
    System.out.println("   state_" + "melodyA1" + "();");
    System.out.println("}\n");

    System.out.println("void state_" + "melodyB1" + "() {");
    System.out.println("   for(int i=0;i<" + 3 + ";i++){");
    System.out.println("       digitalWrite(" + 12 + ", HIGH" + ");");
    System.out.println("       delayMicroseconds(" + 2272 + "/2);");
    System.out.println("       digitalWrite(" + 12 + ", LOW" + ");");
    System.out.println("       delayMicroseconds(" + 2272 + "/2);");
    System.out.println("   }");

    System.out.println("   for(int i=0;i<" + 3 + ";i++){");
    System.out.println("       digitalWrite(" + 12 + ", HIGH" + ");");
    System.out.println("       delayMicroseconds(" + 2028 + "/2);");
    System.out.println("       digitalWrite(" + 12 + ", LOW" + ");");
    System.out.println("       delayMicroseconds(" + 2028 + "/2);");
    System.out.println("   }");

    System.out.println("   boolean guard = millis() - time > debounce;");
    System.out.println("   if (digitalRead(" + 9 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "melodyA2" + "(); ");
    System.out.println("   }");
    System.out.println("   if (digitalRead(" + 10 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "melodyB2" + "(); ");
    System.out.println("   }");
    System.out.println("   state_" + "melodyB1" + "();");
    System.out.println("}\n");

    System.out.println("void state_" + "melodyA2" + "() {");
    System.out.println("   for(int i=0;i<" + 3 + ";i++){");
    System.out.println("       digitalWrite(" + 12 + ", HIGH" + ");");
    System.out.println("       delayMicroseconds(" + 3038 + "/2);");
    System.out.println("       digitalWrite(" + 12 + ", LOW" + ");");
    System.out.println("       delayMicroseconds(" + 3038 + "/2);");
    System.out.println("   }");

    System.out.println("   for(int i=0;i<" + 3 + ";i++){");
    System.out.println("       digitalWrite(" + 12 + ", HIGH" + ");");
    System.out.println("       delayMicroseconds(" + 2864 + "/2);");
    System.out.println("       digitalWrite(" + 12 + ", LOW" + ");");
    System.out.println("       delayMicroseconds(" + 2864 + "/2);");
    System.out.println("   }");

    System.out.println("   boolean guard = millis() - time > debounce;");
    System.out.println("   if (digitalRead(" + 9 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "off" + "(); ");
    System.out.println("   }");
    System.out.println("   if (digitalRead(" + 10 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "off" + "(); ");
    System.out.println("   }");
    System.out.println("   state_" + "melodyA2" + "();");
    System.out.println("}\n");

    System.out.println("void state_" + "melodyB2" + "() {");
    System.out.println("   for(int i=0;i<" + 3 + ";i++){");
    System.out.println("       digitalWrite(" + 12 + ", HIGH" + ");");
    System.out.println("       delayMicroseconds(" + 2550 + "/2);");
    System.out.println("       digitalWrite(" + 12 + ", LOW" + ");");
    System.out.println("       delayMicroseconds(" + 2550 + "/2);");
    System.out.println("   }");

    System.out.println("   for(int i=0;i<" + 3 + ";i++){");
    System.out.println("       digitalWrite(" + 12 + ", HIGH" + ");");
    System.out.println("       delayMicroseconds(" + 1912 + "/2);");
    System.out.println("       digitalWrite(" + 12 + ", LOW" + ");");
    System.out.println("       delayMicroseconds(" + 1912 + "/2);");
    System.out.println("   }");

    System.out.println("   boolean guard = millis() - time > debounce;");
    System.out.println("   if (digitalRead(" + 9 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "off" + "(); ");
    System.out.println("   }");
    System.out.println("   if (digitalRead(" + 10 + ") == " + "HIGH" + " && guard ) {");
    System.out.println("     time = millis(); state_" + "off" + "(); ");
    System.out.println("   }");
    System.out.println("   state_" + "melodyB2" + "();");
    System.out.println("}\n");


    System.out.println("\nvoid loop() { state_" + "off" + "(); } // Entering init state\n");



  }
}
